"use client";

import { Sparkles, TrendingUp, AlertTriangle, Target } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";
import { Separator } from "~/components/ui/separator";

interface CandidateSummary {
  strengths?: string[];
  gaps?: string[];
  risk_flags?: string[];
  overall_assessment?: string;
}

interface CandidateSummaryCardProps {
  summary: CandidateSummary | null | undefined;
  candidateName?: string;
}

export const CandidateSummaryCard = ({ summary, candidateName }: CandidateSummaryCardProps) => {
  if (!summary || (!summary.strengths && !summary.gaps && !summary.risk_flags)) {
    return null;
  }

  const strengths = summary.strengths || [];
  const gaps = summary.gaps || [];
  const riskFlags = summary.risk_flags || [];
  const assessment = summary.overall_assessment || "";

  return (
    <Card className="border-blue-200 bg-gradient-to-br from-blue-50 to-white">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-600" />
            <CardTitle className="text-lg font-semibold">AI Candidate Summary</CardTitle>
          </div>
          <Badge variant="default" className="bg-blue-500 hover:bg-blue-500 text-white">
            <Sparkles className="h-3 w-3 mr-1" /> AI-Assisted
          </Badge>
        </div>
        <CardDescription>
          {candidateName ? `AI-generated insights for ${candidateName}` : "AI-generated candidate insights"}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Overall Assessment */}
        {assessment && (
          <div className="space-y-2">
            <h4 className="text-sm font-semibold text-gray-700 flex items-center gap-2">
              <Target className="h-4 w-4 text-blue-600" />
              Overall Assessment
            </h4>
            <p className="text-sm text-gray-600 bg-white p-3 rounded-md border border-blue-100">
              {assessment}
            </p>
          </div>
        )}

        {/* Strengths */}
        {strengths.length > 0 && (
          <div className="space-y-2">
            <h4 className="text-sm font-semibold text-green-700 flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-green-600" />
              Strengths ({strengths.length})
            </h4>
            <ul className="space-y-1.5">
              {strengths.map((strength, index) => (
                <li key={index} className="text-sm text-gray-700 flex items-start gap-2">
                  <span className="text-green-600 mt-1">✓</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Gaps */}
        {gaps.length > 0 && (
          <div className="space-y-2">
            <Separator />
            <h4 className="text-sm font-semibold text-orange-700 flex items-center gap-2">
              <Target className="h-4 w-4 text-orange-600" />
              Development Areas ({gaps.length})
            </h4>
            <ul className="space-y-1.5">
              {gaps.map((gap, index) => (
                <li key={index} className="text-sm text-gray-700 flex items-start gap-2">
                  <span className="text-orange-600 mt-1">→</span>
                  <span>{gap}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Risk Flags */}
        {riskFlags.length > 0 && (
          <div className="space-y-2">
            <Separator />
            <h4 className="text-sm font-semibold text-red-700 flex items-center gap-2">
              <AlertTriangle className="h-4 w-4 text-red-600" />
              Risk Flags ({riskFlags.length})
            </h4>
            <ul className="space-y-1.5">
              {riskFlags.map((flag, index) => (
                <li key={index} className="text-sm text-gray-700 flex items-start gap-2">
                  <span className="text-red-600 mt-1">⚠</span>
                  <span>{flag}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* AI Disclosure */}
        <Separator />
        <p className="text-xs text-gray-500 italic">
          This summary was generated by AI based on the candidate's resume. It is for informational purposes only and should be used as a starting point for evaluation.
        </p>
      </CardContent>
    </Card>
  );
};

